FLASK_SECRET_KEY = 'development'

DATABASE_IP = '172.18.0.2'
DATABASE_PORT = 9200
INDEX_USERS = 'logintable'
INDEX_LOCATIONS = 'locations'
INDEX_DATASETS = 'datasets'
INDEX_DOMAINS = 'domains'
INDEX_TAGS = 'tags'
INDEX_COMMENTS = 'comments'
INDEX_ID_GENERATOR = 'id_generator'
WAIT_FOR = 'wait_for'

UPLOAD_FOLDER_PATH = './uploadFiles'
UPLOAD_FILE_ALLOWED_EXTENSIONS = ['csv', 'zip', 'tar.gz', 'jpg']
UPLOAD_FILE_SIZE_MAX = 100 * 1000 * 1000  # 100 MB
FLASK_STATIC_FOLDER = "../static"
FLASK_TEMPLATE_FOLDER = "../static/dist"  # images

CKAN_INSTANCE_BASE_URL = 'http://0.0.0.0:5000/api'
CKAN_INSTANCE_JWT = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3VWl0d0lVb1Y5VjhfNWRuWkY0Y2NDNEZDSlR6STc5SFRVXzJucTdXU25tSEdmVVNUN19qSkV4OURXaGpzdUotOXVuVnYtMjZsMmM1cU84ZCIsImlhdCI6MTYyMDEyMjgzNX0.btFdg7UB4-khdZkILJR5DiTRV2cxtf6wjfGwnVR154c'
CKAN_INSTANCE_ORG_ID = '1161da6b-d141-45c2-8efe-3a575b85e70e'

SOFT_DELETE = True
CLEANUP_DATASETS_ENABLED = False
CLEANUP_DATASETS_DAYS = 30