version: '3'

services:

    postgres-dev-crescdi:
        image: postgres:alpine
        container_name: postgres_container_crescdi
        ports:
            - "5005:5432"
        restart: always
        environment:
            POSTGRES_DB: database
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
        networks:
            important_default:
                ipv4_address: 10.21.0.4
    
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "5003:5003"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            important_default:
                ipv4_address: 10.21.0.9

networks:
    important_default:
        ipam:
            driver: default
            config:
                - subnet: 10.21.0.0/16




